In [14]:
import pandas as pd
import numpy as np

In [10]:
data = pd.read_csv('classification_data.csv')
data = data.iloc[:, 2:]
data.head()

2021-03-17 00:00:00  2021-03-18 00:00:00  2021-03-19 00:00:00  \
0            62.450000            60.820000            60.770000   
1            25.160000            24.700000            24.970000   
2            73.200000            70.590000            70.780000   
3            21.180000            20.700000            21.000000   
4            49.977901            48.729444            48.551093   

   2021-03-22 00:00:00  2021-03-23 00:00:00  2021-03-24 00:00:00  \
0            58.330000            54.360000             53.83000   
1            23.830000            22.270000             21.81000   
2            68.560000            65.660000             65.42000   
3            19.200000            19.250000             18.79000   
4            47.530529            45.221875             45.19215   

   2021-03-25 00:00:00  2021-03-26 00:00:00  2021-03-29 00:00:00  \
0            56.050000            56.830000            56.200000   
1            22.770000            22.930000            22.910000   
2            67.750000            68.320000            67.500000   
3            19.640000            19.690000            19.590000   
4            46.579324            47.223369            46.886484   

   2021-03-30 00:00:00  ...  2023-12-18 00:00:00  2023-12-19 00:00:00  \
0            58.210000  ...            42.330000            42.420000   
1            24.120000  ...            14.240000            14.300000   
2            69.940000  ...            39.270000            40.200000   
3            20.570000  ...             5.620000             5.710000   
4            48.452009  ...            41.004149            40.974278   

   2023-12-20 00:00:00  2023-12-21 00:00:00  2023-12-22 00:00:00  \
0            41.180000            42.580000            42.550000   
1            13.980000            14.350000            14.310000   
2            40.090000            40.590000            40.680000   
3             5.620000             5.730000             5.760000   
4            40.167736            40.944406            40.954363   

   2023-12-26 00:00:00  2023-12-27 00:00:00  2023-12-28 00:00:00  \
0            42.080000            41.730000            41.970000   
1            14.110000            13.990000            13.980000   
2            40.160000            39.670000            39.920000   
3             5.730000             5.710000             5.780000   
4            40.585943            40.416669            40.456498   

   2023-12-29 00:00:00  label  
0            41.260000      1  
1            13.740000      1  
2            39.070000      1  
3             5.550000      1  
4            40.058206      1  

[5 rows x 704 columns]

In [44]:
from sktime.datatypes._panel._convert import from_2d_array_to_nested
from sklearn.model_selection import train_test_split

X = data.iloc[:, :-1]  # Selecting all columns except the last one as features
y = data.iloc[:, -1]   # Selecting the last column as the label

# convert to sktime format
X_nested = from_2d_array_to_nested(X)
X_train, X_test, Y_train, Y_test = train_test_split(
    X_nested, y, 
    test_size=0.5,        
    random_state=123,      
    stratify=y            
)

In [158]:
from sktime.classification.shapelet_based import ShapeletTransformClassifier
from sklearn.model_selection import GridSearchCV
from sktime.transformations.panel.shapelet_transform import ShapeletTransform

### shaplet transform classifier

In [116]:
time_contract_in_mins = 4

st = ShapeletTransformClassifier(
    transform_limit_in_minutes=time_contract_in_mins,
    n_shapelet_samples=100,
    max_shapelets=10,
    batch_size=20,
    save_transformed_data=True
)

In [117]:
st.fit(X_train, Y_train)

ShapeletTransformClassifier(batch_size=20, max_shapelets=10,
                            n_shapelet_samples=100, save_transformed_data=True,
                            transform_limit_in_minutes=4)

In [118]:
st.score(X_test, Y_test)

0.7666666666666667

In [119]:
from sklearn.metrics import classification_report, confusion_matrix

print( confusion_matrix(Y_test, st.predict(X_test)) )

[[8 1 1]
 [1 8 1]
 [1 2 7]]


In [120]:
print( classification_report(Y_test, st.predict(X_test)) )

              precision    recall  f1-score   support

           1       0.80      0.80      0.80        10
           2       0.73      0.80      0.76        10
           3       0.78      0.70      0.74        10

    accuracy                           0.77        30
   macro avg       0.77      0.77      0.77        30
weighted avg       0.77      0.77      0.77        30



In [68]:
time_contract_in_mins = 4

st1 = ShapeletTransformClassifier(
    transform_limit_in_minutes=time_contract_in_mins,
    n_shapelet_samples=50,
    max_shapelets=10,
    batch_size=20,
    save_transformed_data=True
)

In [69]:
st1.fit(X_train, Y_train)

ShapeletTransformClassifier(batch_size=20, max_shapelets=10,
                            n_shapelet_samples=50, save_transformed_data=True,
                            transform_limit_in_minutes=4)

In [121]:
st1.score(X_test, Y_test)

0.8

In [71]:
print( confusion_matrix(Y_test, st1.predict(X_test)) )

[[7 1 2]
 [0 8 2]
 [0 1 9]]


In [122]:
print( classification_report(Y_test, st1.predict(X_test)) )

              precision    recall  f1-score   support

           1       1.00      0.70      0.82        10
           2       0.80      0.80      0.80        10
           3       0.69      0.90      0.78        10

    accuracy                           0.80        30
   macro avg       0.83      0.80      0.80        30
weighted avg       0.83      0.80      0.80        30



In [72]:
time_contract_in_mins = 4

st2 = ShapeletTransformClassifier(
    transform_limit_in_minutes=time_contract_in_mins,
    n_shapelet_samples=50,
    max_shapelets=15,
    batch_size=20,
    save_transformed_data=True
)

In [73]:
st2.fit(X_train, Y_train)

ShapeletTransformClassifier(batch_size=20, max_shapelets=15,
                            n_shapelet_samples=50, save_transformed_data=True,
                            transform_limit_in_minutes=4)

In [74]:
st2.score(X_test, Y_test)

0.8

In [75]:
print( confusion_matrix(Y_test, st2.predict(X_test)) )

[[8 1 1]
 [0 8 2]
 [1 1 8]]


In [123]:
print( classification_report(Y_test, st2.predict(X_test)) )

              precision    recall  f1-score   support

           1       0.89      0.80      0.84        10
           2       0.80      0.80      0.80        10
           3       0.73      0.80      0.76        10

    accuracy                           0.80        30
   macro avg       0.81      0.80      0.80        30
weighted avg       0.81      0.80      0.80        30



### rocket

In [52]:
from sklearn.linear_model import RidgeClassifierCV #user ridge for smaller sample
from sktime.transformations.panel.rocket import Rocket

In [124]:
rocket = Rocket()  # by default, ROCKET uses 10,000 kernels
rocket.fit(X_train)
X_train_transform = rocket.transform(X_train)
X_train_transform.shape

(30, 20000)

In [125]:
X_train_transform.head()

0         1         2         3         4         5         6      \
0  0.844720  3.246698  0.513514  3.178449  0.000000 -0.273469  0.711238   
1  0.627329  4.770363  0.486486  4.430501  0.007236  0.377875  0.685633   
2  0.538302  6.353869  0.489331  3.909499  0.054993  1.023528  0.628734   
3  0.842650  4.138290  0.644381  3.966517  0.005789  0.288490  0.650071   
4  0.451346  4.145036  0.482219  3.579683  0.030391  0.512201  0.684211   

      7         8         9      ...     19990     19991     19992     19993  \
0  7.377932  0.828054  4.040874  ...  0.348506  4.455694  0.426009  2.326213   
1  5.013644  0.650075  4.914783  ...  0.456615  3.284742  0.430493  4.009915   
2  8.407527  0.641026  8.563477  ...  0.509246  6.213987  0.591928  2.721705   
3  4.763257  0.696833  4.765262  ...  0.422475  2.915008  0.309417  3.136309   
4  5.928728  0.574661  8.825341  ...  0.499289  4.905119  0.484305  4.235130   

      19994     19995     19996      19997     19998     19999  
0  0.971551  1.310455  0.818182   8.271099  0.977240  1.780710  
1  0.953058  1.618592  0.673219   9.676961  0.953058  1.557904  
2  0.844950  3.399629  0.638821  11.845422  0.862020  2.632963  
3  0.964438  1.851329  0.778870   8.863211  0.981508  1.580867  
4  0.889047  1.753507  0.420147  10.931785  0.926031  1.967655  

[5 rows x 20000 columns]

In [126]:
#normalization = false
classifier = RidgeClassifierCV(alphas=np.logspace(-3, 3, 10)) # np.logspace: Return numbers spaced evenly on a log scale
%timeit classifier.fit(X_train_transform, Y_train)

302 ms ± 8.71 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [127]:
X_test_transform = rocket.transform(X_test)

In [128]:
classifier.score(X_test_transform, Y_test)

0.8333333333333334

In [129]:
print( confusion_matrix(Y_test, classifier.predict(X_test_transform)) )

[[8 1 1]
 [1 9 0]
 [0 2 8]]


In [133]:
print( classification_report(Y_test, classifier.predict(X_test_transform)) )

              precision    recall  f1-score   support

           1       0.89      0.80      0.84        10
           2       0.75      0.90      0.82        10
           3       0.89      0.80      0.84        10

    accuracy                           0.83        30
   macro avg       0.84      0.83      0.83        30
weighted avg       0.84      0.83      0.83        30



In [134]:
#standardization = true
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_standardized = scaler.fit_transform(X_train_transform)
X_train_standardized = pd.DataFrame(X_standardized, columns=X_train_transform.columns)

In [135]:
classifier_stan = RidgeClassifierCV(alphas=np.logspace(-3, 3, 10)) # np.logspace: Return numbers spaced evenly on a log scale
%timeit classifier_stan.fit(X_train_standardized, Y_train)

315 ms ± 27.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [136]:
X_t_standardized = scaler.transform(X_test_transform)
X_test_standardized = pd.DataFrame(X_t_standardized, columns=X_test_transform.columns)

In [137]:
classifier_stan.score(X_test_standardized, Y_test)

0.8666666666666667

In [138]:
print( confusion_matrix(Y_test, classifier_stan.predict(X_test_standardized)) )

[[8 1 1]
 [1 9 0]
 [0 1 9]]


In [139]:
print( classification_report(Y_test, classifier_stan.predict(X_test_standardized)) )

              precision    recall  f1-score   support

           1       0.89      0.80      0.84        10
           2       0.82      0.90      0.86        10
           3       0.90      0.90      0.90        10

    accuracy                           0.87        30
   macro avg       0.87      0.87      0.87        30
weighted avg       0.87      0.87      0.87        30



In [100]:
## mini rocket

In [140]:
from sktime.transformations.panel.rocket import MiniRocket
minirocket = MiniRocket()  # by default, MiniRocket uses ~10,000 kernels
minirocket.fit(X_train)
X_train_minitransform = minirocket.transform(X_train)

classifier = RidgeClassifierCV(alphas=np.logspace(-3, 3, 10))
%timeit classifier.fit(X_train_minitransform, Y_train)

321 ms ± 27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [141]:
X_test_minitransform = minirocket.transform(X_test)

In [142]:
classifier.score(X_test_minitransform, Y_test)

0.7666666666666667

In [143]:
print( confusion_matrix(Y_test, classifier.predict(X_test_minitransform)) )

[[7 1 2]
 [0 9 1]
 [2 1 7]]


In [144]:
print( classification_report(Y_test, classifier.predict(X_test_minitransform)) )

              precision    recall  f1-score   support

           1       0.78      0.70      0.74        10
           2       0.82      0.90      0.86        10
           3       0.70      0.70      0.70        10

    accuracy                           0.77        30
   macro avg       0.77      0.77      0.76        30
weighted avg       0.77      0.77      0.76        30



In [145]:
#standardization = true
scaler = StandardScaler()
X_standardized = scaler.fit_transform(X_train_minitransform)
X_train_standardized = pd.DataFrame(X_standardized, columns=X_train_minitransform.columns)

In [146]:
classifier_stan = RidgeClassifierCV(alphas=np.logspace(-3, 3, 10)) # np.logspace: Return numbers spaced evenly on a log scale
%timeit classifier_stan.fit(X_train_standardized, Y_train)

278 ms ± 14.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [147]:
X_t_standardized = scaler.transform(X_test_minitransform)
X_test_standardized = pd.DataFrame(X_t_standardized, columns=X_test_minitransform.columns)

In [148]:
classifier_stan.score(X_test_standardized, Y_test)

0.8

In [149]:
print( confusion_matrix(Y_test, classifier_stan.predict(X_test_standardized)) )

[[8 1 1]
 [0 9 1]
 [1 2 7]]


In [150]:
print( classification_report(Y_test, classifier_stan.predict(X_test_standardized)) )

              precision    recall  f1-score   support

           1       0.89      0.80      0.84        10
           2       0.75      0.90      0.82        10
           3       0.78      0.70      0.74        10

    accuracy                           0.80        30
   macro avg       0.81      0.80      0.80        30
weighted avg       0.81      0.80      0.80        30

